include("triplets/community/arm64-linux-release.cmake")

set(VCPKG_CMAKE_CONFIGURE_OPTIONS "-DOPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX=OFF" "-DIEX_HAVE_CONTROL_REGISTER_SUPPORT=OFF" "-DIEX_HAVE_SIGCONTEXT_CONTROL_REGISTER_SUPPORT=OFF")