on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          submodules: "recursive"

      - name: Build tag
        id: build_tag
        run: |
          IMAGE_DATE="$(date +'%Y-%m-%d')"
          SHORT_SHA="$(git rev-parse --short HEAD)"
          echo "TAG=${IMAGE_DATE}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "DOCKER_IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IS_MAIN=${{ github.ref == 'refs/heads/main' }}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        if: env.IS_MAIN == 'true'
        uses: "docker/login-action@v4"
        with:
          username: "yeicor"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build builder stage with CPU (for caching)
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${{ env.DOCKER_IMAGE_NAME }}:builder-cpu-${{ steps.build_tag.outputs.TAG }} --build-arg CUDA_ENABLED=0 .

      - name: Build CUDA image
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${{ env.DOCKER_IMAGE_NAME }}:cuda-${{ steps.build_tag.outputs.TAG }} --build-arg CUDA_ENABLED=1 .

      - name: Push images
        if: env.IS_MAIN == 'true'
        run: |
          docker push ${{ env.DOCKER_IMAGE_NAME }}:cpu-${{ steps.build_tag.outputs.TAG }}
          docker push ${{ env.DOCKER_IMAGE_NAME }}:cuda-${{ steps.build_tag.outputs.TAG }}
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:cpu-${{ steps.build_tag.outputs.TAG }} ${{ env.DOCKER_IMAGE_NAME }}:cpu-latest
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:cuda-${{ steps.build_tag.outputs.TAG }} ${{ env.DOCKER_IMAGE_NAME }}:cuda-latest
          docker push ${{ env.DOCKER_IMAGE_NAME }}:cpu-latest
          docker push ${{ env.DOCKER_IMAGE_NAME }}:cuda-latest
