on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when pushing to certain branches
  push:
  pull_request:

env:
  DOCKER_USERNAME: "${{ github.actor }}"
  DOCKER_IMAGE_NAME: "${{ env.DOCKER_USERNAME }}/$(basename ${{ github.repository }})"

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true

      - run: |
          IMAGE_DATE="$(date +'%Y-%m-%d')"
          COLMAP_DESC="$(git -C colmap describe --tags || echo "unknown")"
          OPENMVS_DESC="$(git -C openMVS describe --tags || echo "unknown")"
          echo "IMAGE_TAG=${IMAGE_DATE}-colmap-${COLMAP_VERSION}-openmvs-${OPENMVS_VERSION}" >> $GITHUB_ENV
          
      - uses: "docker/setup-buildx-action@v3"

      - uses: "docker/login-action@v3"
        if: github.ref == 'refs/heads/main'
        with:
          username: "${{ env.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          
      - uses: "docker/build-push-action@v6"
        with:
          context: "."
          file: "./Dockerfile"
          push: "${{ github.ref == 'refs/heads/main' }}"
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: "type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache"
          cache-to: "type=registry,ref=${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max"

