on:
  workflow_dispatch:
  push:
    branches: [main, "renovate/*"]
  pull_request:

jobs:
  meta:
    runs-on: ubuntu-24.04
    outputs:
      image: ${{ steps.meta.outputs.image }}
      user: ${{ steps.meta.outputs.user }}
      tag: ${{ steps.meta.outputs.tag }}
      is_push: ${{ steps.meta.outputs.is_push }}
    steps:
      - name: Compute metadata
        id: meta
        run: |
          echo "image=${{ vars.DOCKER_IMAGE_NAME }}" >> $GITHUB_OUTPUT
          echo "user=$(echo "${{ vars.DOCKER_IMAGE_NAME }}" | cut -d'/' -f1)" >> $GITHUB_OUTPUT

          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT

          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "is_push=true" >> $GITHUB_OUTPUT
          else
            echo "is_push=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: meta
    strategy:
      fail-fast: false
      matrix:
        variant: [cpu, cuda]
        arch: [amd64, arm64]
        build_type: [debug, release]
        include:
          # Native runners
          - arch: amd64
            runner: ubuntu-24.04
            platform: linux/amd64
          - arch: arm64
            runner: ubuntu-24.04-arm
            platform: linux/arm64
            arch_tag: arm64
          # Variants
          - variant: cpu
            BASE_IMAGE: mirror.gcr.io/library/ubuntu:24.04
            RUNTIME_IMAGE: mirror.gcr.io/library/ubuntu:24.04
          - variant: cuda
            BASE_IMAGE: mirror.gcr.io/nvidia/cuda:12.9.1-devel-ubuntu24.04
            RUNTIME_IMAGE: mirror.gcr.io/nvidia/cuda:12.9.1-runtime-ubuntu24.04
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Free Disk Space - Ubuntu Runners
        uses: endersonmenezes/free-disk-space@v3
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          remove_tool_cache: true
          remove_swap: true
          remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-*"
          remove_packages_one_command: true
          remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle"
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Set up Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v4
      - name: Download vcpkg cache artifact # FIXME: OOM trying to download to RAM if artifact is too large, waiting for PR merge.
        uses: yeicor/action-download-artifact@v1.0.1
        with:
          name: docker-cache-mounts-${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}
          search_artifacts: true
          path: cache-mounts
          if_no_artifact_found: ignore
          use_unzip: true
      - name: Docker cache mounts (restore)
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mounts
          dockerfile: Dockerfile
          skip-extraction: true # disable post-step (done manually)
      - name: Build
        uses: docker/build-push-action@v7
        timeout-minutes: 240 # 4 hours should be enough even with cache misses in debug and cuda builds
        with:
          context: .
          # The large buildx cache worth it when the small cache mounts exist. Do not use cache-from/cache-to.
          build-args: |
            BASE_IMAGE=${{ matrix.BASE_IMAGE }}
            RUNTIME_IMAGE=${{ matrix.RUNTIME_IMAGE }}
            BUILD_TYPE=${{ matrix.build_type == 'debug' && 'Debug' || 'Release' }}
          push: false
          load: true
          tags: ${{ needs.meta.outputs.image }}:${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.meta.outputs.tag }}
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCDOCKER_BUILD_RECORD_UPLOAD: false
      - name: Docker cache mounts (extract)
        if: "!cancelled()"
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mounts
          dockerfile: Dockerfile
        env:
          STATE_POST: "true" # Hack to force extract = true for the action
      - name: Disable post docker cache mounts (extract) # Hack to prevent double extraction
        run: echo "" > Dockerfile
      - name: Upload docker cache mounts for debugging and future runs
        if: "!cancelled()"
        uses: actions/upload-artifact@v7
        with:
          name: docker-cache-mounts-${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}
          path: |
            cache-mounts
            !cache-mounts/**/*:*
          retention-days: 7
      - name: Save some disk space
        run: |
          rm -rf cache-mounts
      - name: Save built image as artifact
        run: docker save ${{ needs.meta.outputs.image }}:${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.meta.outputs.tag }} -o docker-image-${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.meta.outputs.tag }}.tar
      - name: Upload built image as artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-image-${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.meta.outputs.tag }}
          path: docker-image-${{ matrix.variant }}-${{ matrix.arch }}-${{ matrix.build_type }}-${{ needs.meta.outputs.tag }}.tar
          retention-days: 1

  test:
    needs: [meta, build]
    strategy:
      fail-fast: false
      matrix:
        # variant: [cpu]
        arch: [amd64, arm64]
        # build_type: [debug]
        include:
          # Native runners
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: docker-image-cpu-${{ matrix.arch }}-debug-${{ needs.meta.outputs.tag }}
      - run: docker load -i docker-image-*.tar && rm docker-image-*.tar
      - name: Download Buddha dataset
        run: |
          git clone --depth 1 https://github.com/alicevision/dataset_buddha.git
          mkdir -p test_obj/images
          cp dataset_buddha/buddha_mini6/*.png test_obj/images/
          rm -rf dataset_buddha
      - name: Run docker container for testing
        timeout-minutes: 60
        run: docker run --user $UID:$GID --rm -v ${{ github.workspace }}/test_obj:/work ${{ needs.meta.outputs.image }}:cpu-${{ matrix.arch }}-debug-${{ needs.meta.outputs.tag }} /usr/bin/bash /entrypoint.sh /work -v
      - name: Upload results (fail if missing)
        uses: actions/upload-artifact@v7
        with:
          name: dataset_buddha-test-output-${{ matrix.arch }}
          path: |
            test_obj/colmap
            test_obj/openmvs
          if-no-files-found: error

  publish:
    needs: [meta, test]
    runs-on: ubuntu-24.04
    if: needs.meta.outputs.is_push == 'true'
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: docker-image-*
          merge-multiple: true
      - run: for img in docker-image-*.tar; do docker load -i $img && rm $img; done
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ needs.meta.outputs.user }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push multi-arch manifest
        run: |
          for variant in cpu cuda; do
            for build_type in debug release; do
              # Push individual architecture images. Needed for multi-arch manifest to work.
              docker push ${{ needs.meta.outputs.image }}:${variant}-amd64-${build_type}-${{ needs.meta.outputs.tag }}
              docker push ${{ needs.meta.outputs.image }}:${variant}-arm64-${build_type}-${{ needs.meta.outputs.tag }}

              # Create multi-arch manifest for this variant and build_type
              docker manifest create ${{ needs.meta.outputs.image }}:${variant}-${build_type}-${{ needs.meta.outputs.tag }} --amend ${{ needs.meta.outputs.image }}:${variant}-amd64-${build_type}-${{ needs.meta.outputs.tag }} --amend ${{ needs.meta.outputs.image }}:${variant}-arm64-${build_type}-${{ needs.meta.outputs.tag }}

              # Push multi-arch manifest
              docker manifest push ${{ needs.meta.outputs.image }}:${variant}-${build_type}-${{ needs.meta.outputs.tag }}

              # Also update ${variant}-${build_type}-latest manifest
              docker manifest create ${{ needs.meta.outputs.image }}:${variant}-${build_type}-latest --amend ${{ needs.meta.outputs.image }}:${variant}-amd64-${build_type}-${{ needs.meta.outputs.tag }} --amend ${{ needs.meta.outputs.image }}:${variant}-arm64-${build_type}-${{ needs.meta.outputs.tag }}
              docker manifest push ${{ needs.meta.outputs.image }}:${variant}-${build_type}-latest
            done
          done

  success: # For auto-merging rules
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - run: echo "All checks passed!"
